//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4_Tell.ws_3dCartApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://3dcart.com/", ConfigurationName="ws_3dCartApi.cartAPIAdvancedSoap")]
    public interface cartAPIAdvancedSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/runQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode runQuery(string storeUrl, string userKey, string sqlStatement, string callBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/runQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> runQueryAsync(string storeUrl, string userKey, string sqlStatement, string callBackURL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cartAPIAdvancedSoapChannel : _4_Tell.ws_3dCartApi.cartAPIAdvancedSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cartAPIAdvancedSoapClient : System.ServiceModel.ClientBase<_4_Tell.ws_3dCartApi.cartAPIAdvancedSoap>, _4_Tell.ws_3dCartApi.cartAPIAdvancedSoap {
        
        public cartAPIAdvancedSoapClient() {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPIAdvancedSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPIAdvancedSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode runQuery(string storeUrl, string userKey, string sqlStatement, string callBackURL) {
            return base.Channel.runQuery(storeUrl, userKey, sqlStatement, callBackURL);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> runQueryAsync(string storeUrl, string userKey, string sqlStatement, string callBackURL) {
            return base.Channel.runQueryAsync(storeUrl, userKey, sqlStatement, callBackURL);
        }
    }
}
